import json

with open('data/resources.json') as f:
    existing = json.load(f)

new_resources = [
  {
    "id": "res_157",
    "title": "C++ Full Course – freeCodeCamp (YouTube)",
    "url": "https://www.youtube.com/watch?v=vLnPwxZdW4Y",
    "type": "Video",
    "tags": ["Free", "YouTube", "Beginner", "Global"],
    "subjects": ["C++ Programming", "Object-Oriented Programming"],
    "skills": ["C++ Programming", "OOP", "Object-Oriented Programming (OOP)"],
    "branches": ["CSE", "ECE", "ME"],
    "description": "freeCodeCamp 4-hour C++ full course covering variables, OOP, templates, STL and memory management."
  },
  {
    "id": "res_158",
    "title": "TypeScript Full Course – freeCodeCamp (YouTube)",
    "url": "https://www.youtube.com/watch?v=30LWjhZzg50",
    "type": "Video",
    "tags": ["Free", "YouTube", "Intermediate", "Global"],
    "subjects": ["TypeScript"],
    "skills": ["TypeScript", "JavaScript"],
    "branches": ["CSE", "IT"],
    "description": "freeCodeCamp 3-hour TypeScript course covering types, interfaces, generics, and advanced patterns."
  },
  {
    "id": "res_159",
    "title": "Go Programming Language – Official Tour",
    "url": "https://go.dev/tour/welcome/1",
    "type": "Course",
    "tags": ["Free", "Official", "Beginner", "Global"],
    "subjects": ["Go Programming"],
    "skills": ["Go (Golang)"],
    "branches": ["CSE", "IT"],
    "description": "Official interactive Go tour by the Go team — covers basics, concurrency and web server patterns."
  },
  {
    "id": "res_160",
    "title": "Rust Book – Official (free online)",
    "url": "https://doc.rust-lang.org/book/",
    "type": "Notes",
    "tags": ["Free", "Official", "Beginner", "Global"],
    "subjects": ["Rust Programming"],
    "skills": ["Rust"],
    "branches": ["CSE"],
    "description": "The official Rust programming language book — ownership, borrowing, lifetimes, traits and concurrency."
  },
  {
    "id": "res_161",
    "title": "Kotlin for Android – Android Developers (Official)",
    "url": "https://developer.android.com/kotlin/learn",
    "type": "Course",
    "tags": ["Free", "Official", "Beginner", "Global"],
    "subjects": ["Kotlin Programming", "Android Development"],
    "skills": ["Kotlin", "Android Development"],
    "branches": ["CSE", "IT"],
    "description": "Google's official Kotlin learning path for Android developers — codelabs, guides and Jetpack Compose."
  },
  {
    "id": "res_162",
    "title": "React – Official Tutorial (react.dev)",
    "url": "https://react.dev/learn",
    "type": "Course",
    "tags": ["Free", "Official", "Beginner", "Global"],
    "subjects": ["React", "Frontend Development"],
    "skills": ["React", "JavaScript (Frontend)", "Frontend Development"],
    "branches": ["CSE", "IT"],
    "description": "Official React documentation and tutorial — components, state, hooks, context and tic-tac-toe project."
  },
  {
    "id": "res_163",
    "title": "Next.js Learn – Official Tutorial",
    "url": "https://nextjs.org/learn",
    "type": "Course",
    "tags": ["Free", "Official", "Intermediate", "Global"],
    "subjects": ["Next.js", "Full Stack Development"],
    "skills": ["Next.js", "React", "Full Stack Development"],
    "branches": ["CSE", "IT"],
    "description": "Official Next.js interactive tutorial covering App Router, server components, databases and deployment."
  },
  {
    "id": "res_164",
    "title": "Node.js Official Learn Guide",
    "url": "https://nodejs.org/en/learn/getting-started/introduction-to-nodejs",
    "type": "Notes",
    "tags": ["Free", "Official", "Beginner", "Global"],
    "subjects": ["Node.js", "Backend Development"],
    "skills": ["Node.js", "Backend Development"],
    "branches": ["CSE", "IT"],
    "description": "Official Node.js documentation and learning guide — event loop, async/await, modules and HTTP server."
  },
  {
    "id": "res_165",
    "title": "Django Official Tutorial",
    "url": "https://docs.djangoproject.com/en/stable/intro/tutorial01/",
    "type": "Course",
    "tags": ["Free", "Official", "Beginner", "Global"],
    "subjects": ["Django", "Backend Development"],
    "skills": ["Django", "Python", "Backend Development"],
    "branches": ["CSE", "IT", "AI_DS"],
    "description": "Official Django polls app tutorial — models, views, templates, forms and admin interface."
  },
  {
    "id": "res_166",
    "title": "FastAPI Official Tutorial",
    "url": "https://fastapi.tiangolo.com/tutorial/",
    "type": "Course",
    "tags": ["Free", "Official", "Intermediate", "Global"],
    "subjects": ["FastAPI", "REST APIs", "Backend Development"],
    "skills": ["FastAPI", "REST APIs", "Python", "Backend Development"],
    "branches": ["CSE", "IT", "AI_DS"],
    "description": "Official FastAPI tutorial — async endpoints, Pydantic models, OpenAPI docs, OAuth2 and deployment."
  },
  {
    "id": "res_167",
    "title": "GraphQL Official Learning Resources",
    "url": "https://graphql.org/learn/",
    "type": "Notes",
    "tags": ["Free", "Official", "Intermediate", "Global"],
    "subjects": ["GraphQL"],
    "skills": ["GraphQL", "REST APIs"],
    "branches": ["CSE", "IT"],
    "description": "Official GraphQL docs covering queries, mutations, subscriptions, schemas and resolvers."
  },
  {
    "id": "res_168",
    "title": "Flutter – Official Docs & Codelabs",
    "url": "https://docs.flutter.dev/get-started/codelab",
    "type": "Course",
    "tags": ["Free", "Official", "Beginner", "Global"],
    "subjects": ["Flutter", "Mobile Development"],
    "skills": ["Flutter", "Mobile Development", "Dart"],
    "branches": ["CSE", "IT"],
    "description": "Official Flutter codelab — build a cross-platform app from scratch using Dart and Flutter widgets."
  },
  {
    "id": "res_169",
    "title": "Microsoft Azure Fundamentals – Microsoft Learn (AZ-900)",
    "url": "https://learn.microsoft.com/en-us/training/paths/azure-fundamentals/",
    "type": "Course",
    "tags": ["Free", "Official", "Certificate", "Beginner", "Global"],
    "subjects": ["Microsoft Azure", "Cloud Computing"],
    "skills": ["Microsoft Azure", "Cloud Computing"],
    "branches": ["CSE", "IT"],
    "description": "Official Microsoft Learn path for AZ-900 — cloud concepts, Azure services, security and pricing."
  },
  {
    "id": "res_170",
    "title": "Terraform — HashiCorp Official Tutorials",
    "url": "https://developer.hashicorp.com/terraform/tutorials",
    "type": "Course",
    "tags": ["Free", "Official", "Intermediate", "Global"],
    "subjects": ["Terraform / Infrastructure as Code"],
    "skills": ["Terraform / Infrastructure as Code", "DevOps", "Cloud Computing"],
    "branches": ["CSE", "IT"],
    "description": "Official HashiCorp Terraform tutorials — HCL syntax, providers, state management, modules and CI/CD."
  },
  {
    "id": "res_171",
    "title": "Prometheus & Grafana Monitoring – freeCodeCamp (YouTube)",
    "url": "https://www.youtube.com/watch?v=9TJx7QTrTyo",
    "type": "Video",
    "tags": ["Free", "YouTube", "Intermediate", "Global"],
    "subjects": ["Monitoring & Observability"],
    "skills": ["Monitoring & Observability", "DevOps"],
    "branches": ["CSE", "IT"],
    "description": "Practical course on Prometheus metrics collection and Grafana dashboards for application monitoring."
  },
  {
    "id": "res_172",
    "title": "Reinforcement Learning – Spinning Up by OpenAI",
    "url": "https://spinningup.openai.com/en/latest/",
    "type": "Notes",
    "tags": ["Free", "Official", "Intermediate", "Global"],
    "subjects": ["Reinforcement Learning", "Advanced Topics in AI"],
    "skills": ["Reinforcement Learning"],
    "branches": ["CSE", "AI_DS"],
    "description": "OpenAI's free educational resource on deep reinforcement learning — MDP, policy gradient and actor-critic methods."
  },
  {
    "id": "res_173",
    "title": "Interpretable ML / Explainable AI – Christoph Molnar (free book)",
    "url": "https://christophm.github.io/interpretable-ml-book/",
    "type": "Notes",
    "tags": ["Free", "Intermediate", "Global"],
    "subjects": ["Explainable AI", "Responsible AI & Ethics"],
    "skills": ["Explainable AI (XAI)", "Responsible AI"],
    "branches": ["CSE", "AI_DS"],
    "description": "Free open-source book on interpretable machine learning — SHAP, LIME, partial dependence plots and more."
  },
  {
    "id": "res_174",
    "title": "Time Series Forecasting – Kaggle Learn",
    "url": "https://www.kaggle.com/learn/time-series",
    "type": "Course",
    "tags": ["Free", "Certificate", "Intermediate", "Global"],
    "subjects": ["Time Series Analysis"],
    "skills": ["Time Series Analysis"],
    "branches": ["CSE", "AI_DS"],
    "description": "Kaggle's free time series course — trend, seasonality, ARIMA, hybrid models and forecasting with ML."
  },
  {
    "id": "res_175",
    "title": "Penetration Testing with Kali Linux – TryHackMe",
    "url": "https://tryhackme.com/path/outline/jrpentester",
    "type": "Course",
    "tags": ["Free", "Practice", "Intermediate", "Global"],
    "subjects": ["Penetration Testing", "Cybersecurity"],
    "skills": ["Penetration Testing", "Cybersecurity Fundamentals"],
    "branches": ["CSE", "IT"],
    "description": "TryHackMe's Jr Penetration Tester path — OWASP Top 10, network exploitation, privilege escalation."
  },
  {
    "id": "res_176",
    "title": "Application Security – OWASP Top 10 (Official)",
    "url": "https://owasp.org/www-project-top-ten/",
    "type": "Reference",
    "tags": ["Free", "Official", "Intermediate", "Global"],
    "subjects": ["Web Security", "Application Security"],
    "skills": ["Web Security", "Application Security", "Cybersecurity Fundamentals"],
    "branches": ["CSE", "IT"],
    "description": "OWASP official reference covering the Top 10 web application security risks with examples and mitigations."
  },
  {
    "id": "res_177",
    "title": "Figma for UI/UX – Figma Official Tutorials",
    "url": "https://help.figma.com/hc/en-us/articles/360038006813-Figma-tutorials",
    "type": "Course",
    "tags": ["Free", "Official", "Beginner", "Global"],
    "subjects": ["UI/UX Design", "Figma"],
    "skills": ["UI/UX Design", "Figma"],
    "branches": ["CSE", "IT"],
    "description": "Official Figma tutorials covering design basics, auto-layout, components, prototyping and developer handoff."
  },
  {
    "id": "res_178",
    "title": "Google UX Design Certificate – Coursera",
    "url": "https://www.coursera.org/professional-certificates/google-ux-design",
    "type": "Course",
    "tags": ["Free", "Certificate", "Beginner", "Global"],
    "subjects": ["UI/UX Design"],
    "skills": ["UI/UX Design", "UX Research"],
    "branches": ["CSE", "IT"],
    "description": "Google's 7-course UX design certificate — user research, wireframing, Figma prototyping and portfolio."
  },
  {
    "id": "res_179",
    "title": "Canva Design School – Free Courses",
    "url": "https://www.canva.com/designschool/courses/",
    "type": "Course",
    "tags": ["Free", "Beginner", "Global"],
    "subjects": ["Graphic Design", "Content Creation"],
    "skills": ["Graphic Design", "Canva", "Content Creation"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "Free Canva design courses covering logo design, social media graphics, presentations and branding."
  },
  {
    "id": "res_180",
    "title": "DaVinci Resolve Official Tutorials (Video Editing)",
    "url": "https://www.blackmagicdesign.com/products/davinciresolve/training",
    "type": "Course",
    "tags": ["Free", "Official", "Beginner", "Global"],
    "subjects": ["Video Editing"],
    "skills": ["Video Editing"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "Official Blackmagic Design training for DaVinci Resolve — free professional video editing software with certification."
  },
  {
    "id": "res_181",
    "title": "Digital Marketing – Google Digital Garage (Free Certificate)",
    "url": "https://learndigital.withgoogle.com/digitalgarage/course/digital-marketing",
    "type": "Course",
    "tags": ["Free", "Certificate", "Beginner", "Global"],
    "subjects": ["Digital Marketing", "SEO", "Content Creation"],
    "skills": ["Digital Marketing", "SEO", "Content Creation"],
    "branches": ["CSE", "IT", "AI_DS"],
    "description": "Google's free 40-hour digital marketing course — SEO, SEM, social, analytics and content marketing with certificate."
  },
  {
    "id": "res_182",
    "title": "Resume Writing – Coursera (SUNY)",
    "url": "https://www.coursera.org/learn/how-to-write-a-resume",
    "type": "Course",
    "tags": ["Free", "Certificate", "Beginner", "Global"],
    "subjects": ["Resume & CV Writing"],
    "skills": ["Resume & CV Writing"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "SUNY coursera course on crafting a compelling resume — formatting, keyword optimization and ATS compatibility."
  },
  {
    "id": "res_183",
    "title": "LinkedIn Profile Optimization – LinkedIn Official Guide",
    "url": "https://www.linkedin.com/help/linkedin/answer/a567129",
    "type": "Reference",
    "tags": ["Free", "Official", "Beginner", "Global"],
    "subjects": ["LinkedIn Profile Optimization"],
    "skills": ["LinkedIn Profile Optimization"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "LinkedIn's official guide to completing and optimising your profile for recruiter visibility."
  },
  {
    "id": "res_184",
    "title": "Technical Interview Preparation – LeetCode Interview Crash Course",
    "url": "https://leetcode.com/explore/interview/card/cheatsheets/720/resources/",
    "type": "Reference",
    "tags": ["Free", "Practice", "Intermediate", "Global"],
    "subjects": ["Technical Interview Preparation"],
    "skills": ["Technical Interview Preparation", "Data Structures & Algorithms (DSA)"],
    "branches": ["CSE", "IT", "AI_DS"],
    "description": "LeetCode's free interview cheat sheet — data structure complexities, problem patterns and approach guides."
  },
  {
    "id": "res_185",
    "title": "GATE Preparation – NPTEL Gate Content",
    "url": "https://nptel.ac.in/courses/106/105/106105253/",
    "type": "Course",
    "tags": ["Free", "Government", "Certificate", "Advanced", "India"],
    "subjects": ["GATE / GRE Preparation"],
    "skills": ["GATE / GRE Preparation"],
    "branches": ["CSE", "IT", "ECE", "EEE", "ME", "CE"],
    "description": "NPTEL NOC course specifically designed for GATE CS preparation — all core subjects covered systematically."
  },
  {
    "id": "res_186",
    "title": "GRE Preparation – Khan Academy Verbal & Quant",
    "url": "https://www.khanacademy.org/test-prep/gre",
    "type": "Course",
    "tags": ["Free", "Beginner", "Global"],
    "subjects": ["GATE / GRE Preparation", "Higher Studies Planning (MS/MBA)"],
    "skills": ["GATE / GRE Preparation", "Higher Studies Planning (MS/MBA)"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "Khan Academy free GRE prep — verbal reasoning, quantitative reasoning and analytical writing."
  },
  {
    "id": "res_187",
    "title": "Freelancing Guide – Internshala Freelancing Training",
    "url": "https://trainings.internshala.com/freelancing-training/",
    "type": "Course",
    "tags": ["Free", "Certificate", "Beginner", "India"],
    "subjects": ["Freelancing Basics"],
    "skills": ["Freelancing Basics"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "Free Internshala course on freelancing basics — building a profile, finding clients and managing projects."
  },
  {
    "id": "res_188",
    "title": "Entrepreneurship – YC Startup School (Free)",
    "url": "https://www.startupschool.org/",
    "type": "Course",
    "tags": ["Free", "Beginner", "Global"],
    "subjects": ["Entrepreneurship & Startups"],
    "skills": ["Entrepreneurship & Startups", "Entrepreneurship Mindset"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "Y Combinator's free Startup School — product market fit, funding, pitching, growth and founder advice."
  },
  {
    "id": "res_189",
    "title": "Presentation Skills – Coursera (University of Washington)",
    "url": "https://www.coursera.org/learn/presentation-skills",
    "type": "Course",
    "tags": ["Free", "Certificate", "Beginner", "Global"],
    "subjects": ["Presentation Skills"],
    "skills": ["Presentation Skills", "Public Speaking"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "Coursera course on crafting and delivering effective presentations — structure, storytelling and slide design."
  },
  {
    "id": "res_190",
    "title": "AI Literacy – Elements of AI (Reaktor / University of Helsinki)",
    "url": "https://www.elementsofai.com/",
    "type": "Course",
    "tags": ["Free", "Certificate", "Beginner", "Global"],
    "subjects": ["AI Literacy for Professionals"],
    "skills": ["AI Literacy for Professionals"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "Free University of Helsinki course explaining AI concepts, limitations and societal impacts for non-technical learners."
  },
  {
    "id": "res_191",
    "title": "Professional Email Writing – Coursera (English for Business)",
    "url": "https://www.coursera.org/learn/business-english-emails",
    "type": "Course",
    "tags": ["Free", "Certificate", "Beginner", "Global"],
    "subjects": ["Professional Email Writing"],
    "skills": ["Professional Email Writing"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "Coursera business English emails course — structure, tone, subject lines and effective professional communication."
  },
  {
    "id": "res_192",
    "title": "Active Listening & Communication – Coursera (UCI)",
    "url": "https://www.coursera.org/learn/communication-listening",
    "type": "Course",
    "tags": ["Free", "Certificate", "Beginner", "Global"],
    "subjects": ["Active Listening", "Communication — Verbal"],
    "skills": ["Active Listening", "Communication — Verbal"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "UCI Coursera course on active listening skills, verbal communication and effective workplace conversations."
  },
  {
    "id": "res_193",
    "title": "Emotional Intelligence – Coursera (UC Davis)",
    "url": "https://www.coursera.org/learn/emotional-intelligence-leadership",
    "type": "Course",
    "tags": ["Free", "Certificate", "Beginner", "Global"],
    "subjects": ["Emotional Intelligence"],
    "skills": ["Emotional Intelligence"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "UC Davis Coursera course on emotional intelligence for leadership — self-awareness, empathy and social skills."
  },
  {
    "id": "res_194",
    "title": "Leadership & Teamwork – Coursera (University of Michigan)",
    "url": "https://www.coursera.org/learn/leading-teams",
    "type": "Course",
    "tags": ["Free", "Certificate", "Beginner", "Global"],
    "subjects": ["Teamwork & Collaboration", "Leadership Basics"],
    "skills": ["Teamwork & Collaboration", "Leadership Basics"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "Michigan Coursera course on leading teams — motivation, conflict, decision making and team dynamics."
  },
  {
    "id": "res_195",
    "title": "Critical Thinking & Decision Making – edX (Rochester)",
    "url": "https://www.edx.org/learn/critical-thinking/rochester-critical-thinking-problem-solving-and-decision-making",
    "type": "Course",
    "tags": ["Free", "Certificate", "Beginner", "Global"],
    "subjects": ["Critical Thinking", "Decision Making"],
    "skills": ["Critical Thinking", "Decision Making", "Problem Solving"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "Rochester edX course on critical thinking frameworks, cognitive biases and structured decision making."
  },
  {
    "id": "res_196",
    "title": "Time Management – Coursera (UC Irvine)",
    "url": "https://www.coursera.org/learn/work-smarter-not-harder",
    "type": "Course",
    "tags": ["Free", "Certificate", "Beginner", "Global"],
    "subjects": ["Time Management", "Productivity Tools (Notion, Trello)"],
    "skills": ["Time Management", "Productivity Tools (Notion, Trello)"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "UC Irvine Coursera course on working smarter — prioritisation, focus strategies and productivity tools."
  },
  {
    "id": "res_197",
    "title": "Financial Literacy – NPTEL (IIT Roorkee)",
    "url": "https://nptel.ac.in/courses/117/107/117107114/",
    "type": "Course",
    "tags": ["Free", "Government", "Certificate", "Beginner", "India"],
    "subjects": ["Financial Literacy"],
    "skills": ["Financial Literacy"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "NPTEL personal finance course — budgeting, SIP investing, taxation, insurance and wealth creation."
  },
  {
    "id": "res_198",
    "title": "Learning How to Learn – Coursera (McMaster University)",
    "url": "https://www.coursera.org/learn/learning-how-to-learn",
    "type": "Course",
    "tags": ["Free", "Certificate", "Beginner", "Global"],
    "subjects": ["Learning How to Learn", "Habit Building"],
    "skills": ["Learning How to Learn", "Habit Building"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "Most enrolled Coursera course ever — memory, procrastination, focused vs diffuse thinking and spaced repetition."
  },
  {
    "id": "res_199",
    "title": "Negotiation – Coursera (Yale)",
    "url": "https://www.coursera.org/learn/negotiation",
    "type": "Course",
    "tags": ["Free", "Certificate", "Beginner", "Global"],
    "subjects": ["Negotiation"],
    "skills": ["Negotiation"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "Yale Coursera course on negotiation fundamentals — BATNA, claiming value, deal structure and ethics."
  },
  {
    "id": "res_200",
    "title": "Software Testing – NPTEL (IIT Bombay)",
    "url": "https://nptel.ac.in/courses/106/101/106101200/",
    "type": "Course",
    "tags": ["Free", "Government", "Certificate", "Intermediate", "India"],
    "subjects": ["Software Testing"],
    "skills": ["Software Testing"],
    "branches": ["CSE", "IT"],
    "description": "NPTEL course on software testing — unit, integration, system and acceptance testing, TDD, code coverage."
  },
  {
    "id": "res_201",
    "title": "REST API Design – RESTful Web Services (Udemy Open)",
    "url": "https://www.udemy.com/course/rest-api/",
    "type": "Course",
    "tags": ["Paid", "Certificate", "Beginner", "Global"],
    "subjects": ["REST APIs", "Backend Development"],
    "skills": ["REST APIs", "Backend Development"],
    "branches": ["CSE", "IT"],
    "description": "Comprehensive Udemy REST API course covering HTTP methods, status codes, authentication and best practices."
  },
  {
    "id": "res_202",
    "title": "Python for Data Science – IBM (Coursera)",
    "url": "https://www.coursera.org/learn/python-for-applied-data-science-ai",
    "type": "Course",
    "tags": ["Free", "Certificate", "Beginner", "Global"],
    "subjects": ["Python for Data Science", "Data Analysis"],
    "skills": ["Python for Data Science", "Data Analysis"],
    "branches": ["CSE", "IT", "AI_DS"],
    "description": "IBM's Python for Data Science course on Coursera — NumPy, Pandas, Matplotlib and real-world data projects."
  },
  {
    "id": "res_203",
    "title": "Debugging Techniques – Missing CS Semester (MIT)",
    "url": "https://missing.csail.mit.edu/2020/debugging-profiling/",
    "type": "Notes",
    "tags": ["Free", "Official", "Intermediate", "Global"],
    "subjects": ["Debugging"],
    "skills": ["Debugging", "Software Testing"],
    "branches": ["CSE", "IT", "AI_DS"],
    "description": "MIT's Missing Semester lecture on debugging and profiling — GDB, pdb, strace and performance profiling."
  },
  {
    "id": "res_204",
    "title": "OOP Concepts – GeeksforGeeks",
    "url": "https://www.geeksforgeeks.org/object-oriented-programming-oops-concept-in-java/",
    "type": "Article",
    "tags": ["Free", "Beginner", "India"],
    "subjects": ["Object-Oriented Programming", "Object-Oriented Programming (Java)"],
    "skills": ["Object-Oriented Programming (OOP)", "Java"],
    "branches": ["CSE", "IT", "AI_DS"],
    "description": "Comprehensive GeeksforGeeks guide to OOP concepts — classes, objects, inheritance, polymorphism, encapsulation and abstraction."
  },
  {
    "id": "res_205",
    "title": "Personal Branding for Engineers – LinkedIn Learning (Free Trial)",
    "url": "https://www.linkedin.com/learning/personal-branding-for-your-career",
    "type": "Course",
    "tags": ["Paid", "Certificate", "Beginner", "Global"],
    "subjects": ["Personal Branding Online"],
    "skills": ["Personal Branding Online"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "LinkedIn Learning course on personal branding — online presence, thought leadership and professional reputation."
  },
  {
    "id": "res_206",
    "title": "HR Interview Preparation – InterviewBit",
    "url": "https://www.interviewbit.com/hr-interview-questions/",
    "type": "Reference",
    "tags": ["Free", "Beginner", "India"],
    "subjects": ["HR Interview & Behavioural Questions"],
    "skills": ["HR Interview & Behavioural Questions", "Technical Interview Preparation"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "InterviewBit comprehensive guide to HR interview questions with STAR-method sample answers."
  },
  {
    "id": "res_207",
    "title": "Group Discussion Skills – Unstop Guide",
    "url": "https://unstop.com/blog/group-discussion-tips",
    "type": "Article",
    "tags": ["Free", "Beginner", "India"],
    "subjects": ["Group Discussion Skills"],
    "skills": ["Group Discussion Skills", "Communication — Verbal"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "Comprehensive guide to group discussion preparation — topics, participation strategies and evaluation criteria."
  },
  {
    "id": "res_208",
    "title": "Agile & Scrum – Scrum Alliance Free Resources",
    "url": "https://www.scrumalliance.org/learn-about-scrum",
    "type": "Reference",
    "tags": ["Free", "Official", "Beginner", "Global"],
    "subjects": ["Agile / Scrum Basics"],
    "skills": ["Agile / Scrum Basics"],
    "branches": ["CSE", "IT"],
    "description": "Scrum Alliance's free guide to Agile and Scrum — roles, ceremonies, artifacts and the Scrum Guide."
  },
  {
    "id": "res_209",
    "title": "Open Source Contribution – GitHub Open Source Guides",
    "url": "https://opensource.guide/how-to-contribute/",
    "type": "Reference",
    "tags": ["Free", "Official", "Beginner", "Global"],
    "subjects": ["Open Source Contribution"],
    "skills": ["Open Source Contribution", "Git & GitHub"],
    "branches": ["CSE", "IT", "AI_DS"],
    "description": "GitHub's official guide to contributing to open source — finding projects, making PRs and community etiquette."
  },
  {
    "id": "res_210",
    "title": "Competitive Programming – Codeforces Educational Content",
    "url": "https://codeforces.com/edu/courses",
    "type": "Course",
    "tags": ["Free", "Practice", "Intermediate", "Global"],
    "subjects": ["Competitive Programming Strategy"],
    "skills": ["Competitive Programming Strategy", "Data Structures & Algorithms (DSA)"],
    "branches": ["CSE", "IT", "AI_DS"],
    "description": "Codeforces EDU courses on algorithms and data structures — segment trees, DSU, strings, flows and more."
  },
  {
    "id": "res_211",
    "title": "Workshop Technology & Manufacturing – NPTEL (IIT Bombay)",
    "url": "https://nptel.ac.in/courses/112/105/112105011/",
    "type": "Course",
    "tags": ["Free", "Government", "Certificate", "Beginner", "India"],
    "subjects": ["Workshop Technology", "Workshop Practice"],
    "skills": ["Manufacturing", "Workshop Skills"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "NPTEL workshop technology course covering basic machining, fitting, welding and carpentry operations."
  },
  {
    "id": "res_212",
    "title": "Automobile Engineering – NPTEL",
    "url": "https://nptel.ac.in/courses/112/105/112105244/",
    "type": "Course",
    "tags": ["Free", "Government", "Certificate", "Intermediate", "India"],
    "subjects": ["Automobile Engineering"],
    "skills": ["Automobile Engineering", "IC Engines"],
    "branches": ["ME"],
    "description": "NPTEL course on automobile systems — IC engines, transmission, suspension, brakes and vehicle dynamics."
  },
  {
    "id": "res_213",
    "title": "Non-Destructive Testing – NPTEL (IIT Kharagpur)",
    "url": "https://nptel.ac.in/courses/112/105/112105139/",
    "type": "Course",
    "tags": ["Free", "Government", "Certificate", "Intermediate", "India"],
    "subjects": ["Non-Destructive Testing"],
    "skills": ["Non-Destructive Testing (NDT)", "Quality Control"],
    "branches": ["ME"],
    "description": "NPTEL course on NDT methods — ultrasonic, radiography, magnetic particle, eddy current and dye penetrant testing."
  },
  {
    "id": "res_214",
    "title": "Six Sigma & Quality Management – ASQ Free Resources",
    "url": "https://asq.org/quality-resources",
    "type": "Reference",
    "tags": ["Free", "Official", "Intermediate", "Global"],
    "subjects": ["Six Sigma & Quality Management"],
    "skills": ["Six Sigma for Process Industries"],
    "branches": ["CHEM", "ME"],
    "description": "ASQ (American Society for Quality) free quality resources — Six Sigma tools, PDCA, control charts and lean basics."
  },
  {
    "id": "res_215",
    "title": "Process Equipment Design – NPTEL (IIT Bombay)",
    "url": "https://nptel.ac.in/courses/103/102/103102042/",
    "type": "Course",
    "tags": ["Free", "Government", "Certificate", "Advanced", "India"],
    "subjects": ["Process Equipment Design", "Chemical Plant Design"],
    "skills": ["Process Design & Optimization"],
    "branches": ["CHEM"],
    "description": "IIT Bombay NPTEL course on design of heat exchangers, pressure vessels, reactors and distillation columns."
  },
  {
    "id": "res_216",
    "title": "Transport Phenomena – MIT OCW (10.50)",
    "url": "https://ocw.mit.edu/courses/10-50-analysis-of-transport-phenomena-i-mathematical-methods-fall-2006/",
    "type": "Notes",
    "tags": ["Free", "Official", "Advanced", "Global"],
    "subjects": ["Transport Phenomena"],
    "skills": ["Transport Phenomena", "Fluid Mechanics"],
    "branches": ["CHEM"],
    "description": "MIT OCW transport phenomena course — momentum, energy and mass transfer with mathematical methods."
  },
  {
    "id": "res_217",
    "title": "Particle Technology – NPTEL (IIT Madras)",
    "url": "https://nptel.ac.in/courses/103/106/103106117/",
    "type": "Course",
    "tags": ["Free", "Government", "Certificate", "Intermediate", "India"],
    "subjects": ["Particle Technology"],
    "skills": ["Particle Technology", "Chemical Engineering"],
    "branches": ["CHEM"],
    "description": "NPTEL particle technology course — size reduction, classification, mixing, fluidisation and pneumatic conveying."
  },
  {
    "id": "res_218",
    "title": "Genetic Engineering – MIT OCW (7.13)",
    "url": "https://ocw.mit.edu/courses/7-13-experimental-microbial-genetics-fall-2002/",
    "type": "Notes",
    "tags": ["Free", "Official", "Advanced", "Global"],
    "subjects": ["Genetic Engineering"],
    "skills": ["Genetic Engineering Techniques", "Molecular Biology Techniques"],
    "branches": ["BT"],
    "description": "MIT OCW genetics lab — cloning, transformation, PCR and genetic analysis techniques."
  },
  {
    "id": "res_219",
    "title": "Industrial Biotechnology – NPTEL (IIT Roorkee)",
    "url": "https://nptel.ac.in/courses/102/107/102107172/",
    "type": "Course",
    "tags": ["Free", "Government", "Certificate", "Intermediate", "India"],
    "subjects": ["Industrial Biotechnology", "Microbial Biotechnology"],
    "skills": ["Industrial Biotechnology"],
    "branches": ["BT"],
    "description": "NPTEL industrial biotechnology course covering fermentation, enzyme technology and industrial microorganisms."
  },
  {
    "id": "res_220",
    "title": "Plant Biotechnology – NPTEL (IIT Madras)",
    "url": "https://nptel.ac.in/courses/102/106/102106088/",
    "type": "Course",
    "tags": ["Free", "Government", "Certificate", "Intermediate", "India"],
    "subjects": ["Plant Biotechnology"],
    "skills": ["Plant Biotechnology"],
    "branches": ["BT"],
    "description": "NPTEL plant biotechnology course — tissue culture, genetic transformation, molecular markers and GM crops."
  },
  {
    "id": "res_221",
    "title": "Regulatory Affairs in Pharma/Biotech – WHO Resources",
    "url": "https://www.who.int/teams/health-product-and-policy-standards/standards-and-specifications",
    "type": "Reference",
    "tags": ["Free", "Official", "Intermediate", "Global"],
    "subjects": ["Regulatory Affairs & Bioethics"],
    "skills": ["Regulatory Affairs & Bioethics"],
    "branches": ["BT"],
    "description": "WHO's free pharmacopoeia and standards reference for biotech/pharma regulatory requirements."
  },
  {
    "id": "res_222",
    "title": "Analytical Instrumentation – NPTEL (IIT Madras)",
    "url": "https://nptel.ac.in/courses/102/106/102106066/",
    "type": "Course",
    "tags": ["Free", "Government", "Certificate", "Intermediate", "India"],
    "subjects": ["Analytical Instrumentation"],
    "skills": ["Sensor Calibration & Metrology", "Industrial Measurement"],
    "branches": ["EI", "CHEM", "BT"],
    "description": "NPTEL analytical instrumentation course — spectroscopy, chromatography, electrochemistry and thermal analysis."
  },
  {
    "id": "res_223",
    "title": "Biomedical Instrumentation – NPTEL (IIT Madras)",
    "url": "https://nptel.ac.in/courses/108/106/108106118/",
    "type": "Course",
    "tags": ["Free", "Government", "Certificate", "Intermediate", "India"],
    "subjects": ["Biomedical Instrumentation"],
    "skills": ["Biomedical Instrumentation"],
    "branches": ["EI"],
    "description": "NPTEL biomedical instrumentation course — biosignal acquisition, ECG, EEG, patient monitoring and medical imaging."
  },
  {
    "id": "res_224",
    "title": "Information Theory & Coding – NPTEL (IIT Bombay)",
    "url": "https://nptel.ac.in/courses/117/101/117101057/",
    "type": "Course",
    "tags": ["Free", "Government", "Certificate", "Advanced", "India"],
    "subjects": ["Information Theory & Coding"],
    "skills": ["Communication Systems", "Digital Communications"],
    "branches": ["ECE"],
    "description": "IIT Bombay NPTEL information theory course — entropy, channel capacity, source/channel coding and error correction."
  },
  {
    "id": "res_225",
    "title": "Advanced Communication Systems – NPTEL (IIT Madras)",
    "url": "https://nptel.ac.in/courses/117/106/117106044/",
    "type": "Course",
    "tags": ["Free", "Government", "Certificate", "Advanced", "India"],
    "subjects": ["Advanced Communication Systems"],
    "skills": ["Communication Systems", "RF & Wireless Communication"],
    "branches": ["ECE"],
    "description": "IIT Madras advanced communication systems — MIMO, OFDM, spread spectrum and 4G/5G concepts."
  },
  {
    "id": "res_226",
    "title": "Advanced Process Control – NPTEL",
    "url": "https://nptel.ac.in/courses/103/106/103106213/",
    "type": "Course",
    "tags": ["Free", "Government", "Certificate", "Advanced", "India"],
    "subjects": ["Advanced Process Control"],
    "skills": ["Process Control Design"],
    "branches": ["CHEM", "EI"],
    "description": "NPTEL advanced process control — model predictive control, cascade control, Smith predictor and multivariable control."
  },
  {
    "id": "res_227",
    "title": "Advanced Process Design – NPTEL (IIT Bombay)",
    "url": "https://nptel.ac.in/courses/103/102/103102043/",
    "type": "Course",
    "tags": ["Free", "Government", "Certificate", "Advanced", "India"],
    "subjects": ["Advanced Process Design"],
    "skills": ["Process Design & Optimization"],
    "branches": ["CHEM"],
    "description": "IIT Bombay NPTEL advanced process design — integration, simulation, debottlenecking and optimization of chemical plants."
  },
  {
    "id": "res_228",
    "title": "Smart Sensors & MEMS – NPTEL (IIT Bombay)",
    "url": "https://nptel.ac.in/courses/108/101/108101091/",
    "type": "Course",
    "tags": ["Free", "Government", "Certificate", "Advanced", "India"],
    "subjects": ["Smart Sensors & MEMS"],
    "skills": ["Sensor Calibration & Metrology", "Industrial IoT"],
    "branches": ["EI", "ECE"],
    "description": "NPTEL MEMS and microsensors course — fabrication, piezoresistive, capacitive and optical MEMS devices."
  },
  {
    "id": "res_229",
    "title": "Energy Auditing – Bureau of Energy Efficiency (BEE) Guide",
    "url": "https://beeindia.gov.in/content/study-material-3",
    "type": "Reference",
    "tags": ["Free", "Government", "Official", "Intermediate", "India"],
    "subjects": ["Energy Auditing & Management"],
    "skills": ["Energy Auditing & Management"],
    "branches": ["EEE", "ME"],
    "description": "Bureau of Energy Efficiency (India) free study material for energy auditing — power systems, HVAC, lighting and motors."
  },
  {
    "id": "res_230",
    "title": "Linux Administration – The Linux Foundation (Free Intro)",
    "url": "https://training.linuxfoundation.org/training/introduction-to-linux/",
    "type": "Course",
    "tags": ["Free", "Official", "Certificate", "Beginner", "Global"],
    "subjects": ["Linux Administration"],
    "skills": ["Linux & Command Line"],
    "branches": ["CSE", "IT"],
    "description": "Linux Foundation's free Introduction to Linux (LFS101) — commands, file system, shell scripting and system admin basics."
  },
  {
    "id": "res_231",
    "title": "AI Research Methods – Stanford CS229 Notes",
    "url": "https://cs229.stanford.edu/notes2021fall/",
    "type": "Notes",
    "tags": ["Free", "Official", "Advanced", "Global"],
    "subjects": ["AI Research Methods", "Advanced Topics in AI"],
    "skills": ["AI Research Methods"],
    "branches": ["CSE", "AI_DS"],
    "description": "Stanford CS229 Machine Learning lecture notes covering supervised, unsupervised learning and deep learning foundations."
  },
  {
    "id": "res_232",
    "title": "Python for Machine Learning – Google Developers Codelabs",
    "url": "https://codelabs.developers.google.com/",
    "type": "Course",
    "tags": ["Free", "Official", "Intermediate", "Global"],
    "subjects": ["Machine Learning", "Python for Data Science"],
    "skills": ["Machine Learning", "Python for Data Science"],
    "branches": ["CSE", "IT", "AI_DS"],
    "description": "Google Codelabs for ML and TensorFlow — hands-on labs for image classification, NLP and model deployment."
  },
  {
    "id": "res_233",
    "title": "Deep Learning – PyTorch Official Tutorials",
    "url": "https://pytorch.org/tutorials/",
    "type": "Course",
    "tags": ["Free", "Official", "Intermediate", "Global"],
    "subjects": ["Deep Learning", "Deep Learning Architectures"],
    "skills": ["Deep Learning"],
    "branches": ["CSE", "AI_DS"],
    "description": "Official PyTorch tutorials — tensor basics, neural networks, CNNs, RNNs, transfer learning and model deployment."
  },
  {
    "id": "res_234",
    "title": "LLMs & Generative AI – DeepLearning.AI Short Courses",
    "url": "https://learn.deeplearning.ai/",
    "type": "Course",
    "tags": ["Free", "Beginner", "Global"],
    "subjects": ["Generative AI", "AI Agents"],
    "skills": ["Generative AI", "AI Agents", "Prompt Engineering"],
    "branches": ["CSE", "AI_DS"],
    "description": "Andrew Ng's free short courses on LLMs — prompt engineering, LangChain, RAG, agents and fine-tuning."
  },
  {
    "id": "res_235",
    "title": "Excel & Spreadsheets – Microsoft Excel Free Courses (Microsoft Learn)",
    "url": "https://support.microsoft.com/en-us/office/excel-video-training-9bc05390-e94c-46af-a5b3-d7c22f6990bb",
    "type": "Course",
    "tags": ["Free", "Official", "Beginner", "Global"],
    "subjects": ["Data Analysis"],
    "skills": ["Data Analysis"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "Microsoft's official free Excel training videos — formulas, pivot tables, VLOOKUP, charts and data analysis."
  },
  {
    "id": "res_236",
    "title": "Power BI – Microsoft Learn (Free)",
    "url": "https://learn.microsoft.com/en-us/training/powerbi/",
    "type": "Course",
    "tags": ["Free", "Official", "Certificate", "Beginner", "Global"],
    "subjects": ["Data Visualization"],
    "skills": ["Data Visualization"],
    "branches": ["CSE", "IT", "AI_DS"],
    "description": "Microsoft's official Power BI learning path — data modeling, DAX, report building, sharing and Power BI Service."
  },
  {
    "id": "res_237",
    "title": "Tableau Public Free Training",
    "url": "https://www.tableau.com/learn/training/free-training-videos",
    "type": "Course",
    "tags": ["Free", "Official", "Beginner", "Global"],
    "subjects": ["Data Visualization"],
    "skills": ["Data Visualization"],
    "branches": ["CSE", "IT", "AI_DS"],
    "description": "Tableau's official free video training library — connecting data, building charts, dashboards and Tableau Public."
  },
  {
    "id": "res_238",
    "title": "MLflow Experiment Tracking – MLflow Official Docs",
    "url": "https://mlflow.org/docs/latest/tracking.html",
    "type": "Notes",
    "tags": ["Free", "Official", "Intermediate", "Global"],
    "subjects": ["MLOps", "AI Deployment"],
    "skills": ["MLOps"],
    "branches": ["CSE", "AI_DS"],
    "description": "Official MLflow docs for experiment tracking — logging parameters, metrics, artifacts and model registry."
  },
  {
    "id": "res_239",
    "title": "AWS Security – AWS Well-Architected Security Pillar",
    "url": "https://aws.amazon.com/architecture/well-architected/",
    "type": "Reference",
    "tags": ["Free", "Official", "Intermediate", "Global"],
    "subjects": ["Cybersecurity", "Network Security"],
    "skills": ["Application Security", "Cybersecurity Fundamentals"],
    "branches": ["CSE", "IT"],
    "description": "AWS Well-Architected Framework Security Pillar — IAM, data protection, detection, infrastructure and incident response."
  },
  {
    "id": "res_240",
    "title": "DevSecOps – DevSecOps Manifesto & OWASP Resources",
    "url": "https://www.devsecops.org/",
    "type": "Reference",
    "tags": ["Free", "Official", "Intermediate", "Global"],
    "subjects": ["DevSecOps"],
    "skills": ["DevSecOps", "Application Security"],
    "branches": ["CSE", "IT"],
    "description": "DevSecOps manifesto, principles and OWASP SAMM framework for integrating security into CI/CD pipelines."
  },
  {
    "id": "res_241",
    "title": "PCB Design with KiCad – DigiKey / Official Tutorial",
    "url": "https://www.kicad.org/help/learning-resources/",
    "type": "Course",
    "tags": ["Free", "Official", "Beginner", "Global"],
    "subjects": ["PCB Design"],
    "skills": ["PCB Design"],
    "branches": ["ECE"],
    "description": "Official KiCad learning resources — schematic capture, PCB layout, design rules and Gerber file generation."
  },
  {
    "id": "res_242",
    "title": "Internship Search Strategy – Internshala Guide",
    "url": "https://internshala.com/blog/how-to-find-internship/",
    "type": "Article",
    "tags": ["Free", "Beginner", "India"],
    "subjects": ["Internship Search Strategies"],
    "skills": ["Internship Search Strategies"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "Comprehensive guide on finding and applying for internships in India — platforms, tips and application strategies."
  },
  {
    "id": "res_243",
    "title": "Higher Studies Abroad – IITK Guide to MS Applications",
    "url": "https://iitk.ac.in/doaa/guide-for-higher-studies",
    "type": "Reference",
    "tags": ["Free", "Official", "Intermediate", "India"],
    "subjects": ["Higher Studies Planning (MS/MBA)"],
    "skills": ["Higher Studies Planning (MS/MBA)"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "IIT Kanpur's guide to MS/PhD applications abroad — SOP, LoR, GRE, TOEFL and shortlisting universities."
  },
  {
    "id": "res_244",
    "title": "Technical Blogging – Dev.to & Hashnode Getting Started",
    "url": "https://dev.to/",
    "type": "Reference",
    "tags": ["Free", "Beginner", "Global"],
    "subjects": ["Technical Blogging & Portfolio Building"],
    "skills": ["Technical Blogging & Portfolio Building", "Personal Branding Online"],
    "branches": ["CSE", "IT", "AI_DS"],
    "description": "Dev.to free developer blogging platform — write technical posts, build audience and establish online presence."
  },
  {
    "id": "res_245",
    "title": "Public Speaking – Toastmasters International",
    "url": "https://www.toastmasters.org/resources/public-speaking-tips",
    "type": "Reference",
    "tags": ["Free", "Beginner", "Global"],
    "subjects": ["Public Speaking"],
    "skills": ["Public Speaking", "Presentation Skills"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "Toastmasters free public speaking tips — preparation, delivery, body language and overcoming stage fright."
  },
  {
    "id": "res_246",
    "title": "Conflict Resolution – Coursera (Emory)",
    "url": "https://www.coursera.org/learn/conflict-resolution",
    "type": "Course",
    "tags": ["Free", "Certificate", "Beginner", "Global"],
    "subjects": ["Conflict Resolution"],
    "skills": ["Conflict Resolution"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "Emory Coursera course on conflict resolution — mediation, negotiation and constructive conflict management."
  },
  {
    "id": "res_247",
    "title": "Creativity & Innovation – edX (Vanderbilt)",
    "url": "https://www.edx.org/learn/creativity/vanderbilt-university-creativity-and-innovation",
    "type": "Course",
    "tags": ["Free", "Certificate", "Beginner", "Global"],
    "subjects": ["Creativity"],
    "skills": ["Creativity", "Problem Solving"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "Vanderbilt edX course on creativity and innovation — design thinking, ideation techniques and creative confidence."
  },
  {
    "id": "res_248",
    "title": "Discipline & Habit Building – James Clear Atomic Habits (Excerpts)",
    "url": "https://jamesclear.com/habits",
    "type": "Reference",
    "tags": ["Free", "Beginner", "Global"],
    "subjects": ["Habit Building", "Discipline & Consistency"],
    "skills": ["Habit Building", "Discipline & Consistency"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "James Clear's free articles on building habits — habit loops, environment design and compounding consistency."
  },
  {
    "id": "res_249",
    "title": "Mental Health & Resilience – Coursera (Yale) Happiness Science",
    "url": "https://www.coursera.org/learn/the-science-of-well-being",
    "type": "Course",
    "tags": ["Free", "Certificate", "Beginner", "Global"],
    "subjects": ["Resilience & Mental Health"],
    "skills": ["Resilience & Mental Health", "Stress Management"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "Yale's most popular course — the Science of Well-Being — rewiring habits, gratitude, social connection and resilience."
  },
  {
    "id": "res_250",
    "title": "Sales & Persuasion – Coursera (Kellogg / Northwestern)",
    "url": "https://www.coursera.org/learn/art-of-sales-1",
    "type": "Course",
    "tags": ["Free", "Certificate", "Beginner", "Global"],
    "subjects": ["Basic Sales & Persuasion"],
    "skills": ["Basic Sales & Persuasion"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "Northwestern Kellogg sales course — identifying customer needs, pitching, objection handling and closing."
  },
  {
    "id": "res_251",
    "title": "Growth Mindset – Coursera (Stanford Carol Dweck) ",
    "url": "https://www.coursera.org/learn/mindshift",
    "type": "Course",
    "tags": ["Free", "Certificate", "Beginner", "Global"],
    "subjects": ["Learning How to Learn", "Resilience & Mental Health"],
    "skills": ["Growth Mindset", "Learning How to Learn"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "McMaster MindShift course on growth mindset, overcoming imposter syndrome and lifelong learning strategies."
  },
  {
    "id": "res_252",
    "title": "Stress Management – NPTEL (Psychological Wellbeing)",
    "url": "https://nptel.ac.in/courses/109/104/109104068/",
    "type": "Course",
    "tags": ["Free", "Government", "Certificate", "Beginner", "India"],
    "subjects": ["Resilience & Mental Health"],
    "skills": ["Stress Management", "Resilience & Mental Health"],
    "branches": ["CSE", "IT", "AI_DS", "ECE", "EEE", "ME", "CE", "CHEM", "BT", "EI"],
    "description": "NPTEL course on psychological wellbeing — stress, anxiety management, emotional regulation and coping strategies."
  }
]

all_resources = existing + new_resources
with open('data/resources.json', 'w') as f:
    json.dump(all_resources, f, indent=2, ensure_ascii=False)

print(f'Written {len(all_resources)} resources (added {len(new_resources)} new)')
